#!/bin/bash
#SBATCH -t 6-00:00:00
#SBATCH -n 1
STARTTIME=$(date +%Y-%m-%d%t%k:%M:%S:%N)

./run -g -o --terminal

ENDTIME=$(date +%Y-%m-%d%t%k:%M:%S:%N)
echo -e "$SLURM_JOB_ID\t $SLURM_JOB_NAME\t $STARTTIME\t $ENDTIME" >> ./brick.out
