#!/bin/bash

#SBATCH -n 128
#SBATCH --exclusive
#SBATCH -t 2-00:00:00

module load 2021
module load OpenMPI/4.1.1-intel-compilers-2021.2.0 

lmp=~/la*18/src/
srun $lmp/lmp_mpi < simulation.in

wait

exit 0 
